name: Bump version
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: PATCH

    - name: Extract tag name
      id: tag
      run: echo "TAG_NAME=$(echo $GITHUB_REF)"

    - name: Update version in setup.py
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/$GITHUB_OUTPUT/g" setup.py

    - name: Extract tag name2
      id: tag2
      run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

    - name: Update version in setup.py2
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag2.outputs.TAG_NAME }}/g" setup.py
